# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935c558bcb9f2b8f88446439a1a5359f3b286f44911aa5fd810f8ed5d0a7ebc72b9ccce129735f140b9e0ed83820643becc16c995b79241d09305d3a60a3cbee

test:
  secret_key_base: 6ad1981d272954b1b870f1cf44ac110ba078c65e5b09bb03b5b3259675eddd63b462b13496db262f2dd8c3610c858b6e1219ea4e93086430ad5e4ec1c6512176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
